stages:
  - deploy
deploy_dev:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - rm -rf /var/www/polenoviucheniki.ru/*
    - cp -r ./dist/* /var/www/polenoviucheniki.ru
  only:
    - main
cache:
  key: npm-cache
  paths:
    - node_modules/